### ISSUE TITLE
Error while installing on Kodi matrix beta-1 

### ISSUE THREAD

**Issue by batelcho** [BlackGlassSkin/skin.nox.glass#1]
It asks for script.skin.helper.service" version="1.1.31" which is python 2

**Comment by BlackGlassSkin** [comment]
install this repository first

https://github.com/AnonTester/kodi-repo/tree/master/repository.anontester

**Comment by batelcho** [comment]
I removed this lines from addon.xml and it worked :


<import addon="script.skin.helper.service" version="1.1.31" />
        <import addon="script.skin.helper.widgets" version="1.0.42" />
        <import addon="script.image.resource.select" version="3.0.2" />
	    <import addon="script.skin.helper.colorpicker" version="2.0.1"/>
		

The skinhelper addon from the repo you suggested was also python2 dependent 


I suggest you to make lighter color theme and transparency for the other colors. Some of the text of PVR menus are really dark, I've used color xml from aeon nox to achieve something useful to me, with color controls from the settings is not enough
I really like that it has PVR artwork :)

**Comment by BlackGlassSkin** [comment]
The repository I gave is compatible with python 2 and python 3 "skinhelper"
is compatible, but you need to install it from the repo I gave before
installing the skin "it's an important, very important addon"

wt., 8 gru 2020 o 14:43 batelcho <notifications@github.com> napisał(a):
